#!/bin/bash

FLAG="--make -O2 -rtsopts -j4 -threaded -funbox-strict-fields -XBangPatterns -funbox-strict-fields -funbox-strict-fields -fno-liberate-case -funfolding-use-threshold1000 -funfolding-keeness-factor1000 -fllvm -optlo-O3" #
LIBS="-lgomp -lstdc++ -lblas"
OBJPATH="../../Classifier/LibLinear/"

cabal exec -- ghc $FLAG $LIBS -i../../ Main.hs -o main
cabal exec -- ghc $FLAG $LIBS -i../../ WeightVisualization.hs -o weightVisualization
cabal exec -- ghc $FLAG $LIBS -i../../ PlotConvolutionalWeight.hs -o plotConvolutionalWeight
