#!/bin/bash

export OMP_NUM_THREADS=64
FLAG="--make -O2 -rtsopts -j4 -threaded " #-funbox-strict-fields
LIBS="-lgomp -lstdc++ -lblas"
OBJPATH="../../Classifier/LibLinear/"


ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o Train.hs -o train
ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o Test.hs -o test