#!/bin/bash

export OMP_NUM_THREADS=64
FLAG="--make -O2 -rtsopts -j4 -threaded -funbox-strict-fields -fllvm -optlo-O3 -fno-full-laziness -XBangPatterns" #-funbox-strict-fields
LIBS="-lgomp -lstdc++ -lblas"
OBJPATH="../../Classifier/LibLinear/"


cabal exec -- ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o Train.hs -o train
cabal exec -- ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o Test.hs -o test
cabal exec -- ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o TestVoting.hs -o testVoting
