#!/bin/bash

export OMP_NUM_THREADS=28
FLAG="--make -O2 -rtsopts -j4 -threaded " #-funbox-strict-fields
LIBS="-lgomp -lstdc++ -lblas -L/usr/local/cuda-7.5/lib64/stubs"
OBJPATH="../../Classifier/LibLinear/"


ghc $FLAG $LIBS -i../../ Train.hs -o trainGMM
ghc $FLAG $LIBS -i../../ ConvertPVPGMM.hs -o convertPVPGMM
# ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o TrainFisher.hs -o trainFisher
# ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o PredictFisher.hs -o predictFisher
