#!/bin/bash


FLAG="--make -O2 -rtsopts -j4 -threaded -funbox-strict-fields -XBangPatterns" #-funbox-strict-fields
LIBS="-lgomp -lstdc++ -lblas"
OBJPATH="../../Classifier/LibLinear/"


cabal exec -- ghc $FLAG $LIBS -i../../ Train.hs -o trainGMM
# ghc $FLAG $LIBS -i../../ ConvertPVPGMM.hs -o convertPVPGMM
cabal exec -- ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o TrainFisher.hs -o trainFisher &
cabal exec -- ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o PredictFisher.hs -o predictFisher &
cabal exec -- ghc $FLAG $LIBS -i../../ PlotGMMWeight.hs -o plotGMMWeight &
wait
