#!/bin/bash

export OMP_NUM_THREADS=64
FLAG="--make -O2 -rtsopts -j4 -threaded -funbox-strict-fields -fllvm -optlo-O3 -fno-full-laziness -XBangPatterns" #-funbox-strict-fields
LIBS="-lgomp -lstdc++ -lblas -lhdf5 -lhdf5_hl -lprotobuf  -lcaffe" #-lopencv_imgcodecs
OBJPATH="../../Classifier/LibLinear/"


# cabal exec -- ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o Main.hs -o main
# cabal exec -- ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o MainValidate.hs -o mainValidate
# cabal exec -- ghc $FLAG $LIBS -i../../ caffeData.o $OBJPATH/linear.o $OBJPATH/tron.o Image2LMDB.hs -o image2LMDB
# cabal exec -- ghc $FLAG $LIBS -i../../ caffeData.o $OBJPATH/linear.o $OBJPATH/tron.o Image2LMDBFull.hs -o image2LMDBFull
# cabal exec -- ghc $FLAG $LIBS -i../../ $OBJPATH/linear.o $OBJPATH/tron.o PVP2HDF5.hs -o pvp2hdf5

cabal exec -- ghc $FLAG $LIBS -i../../ caffeData.o $OBJPATH/linear.o $OBJPATH/tron.o SizeTest -o sizeTest

