#!/bin/bash

export OMP_NUM_THREADS=14
FLAG="--make -O3 -j4 -threaded -rtsopts -fno-liberate-case -funfolding-use-threshold1000 -funfolding-keeness-factor1000 -fllvm -optlo-O3 -funbox-strict-fields" 
LIBS="-lgomp -lstdc++ -lblas"

cabal exec -- ghc $FLAG $LIBS -i../../ Main.hs -o main
